ballerina-platform/module-ballerinax-health.hl7v2

base/Ballerina.toml, base/Module.md, base/parser.bal
> $Subject.
> Related issue: https://github.com/wso2-enterprise/open-healthcare/issues/1214
=> Add parser to support HL7 messages in string format

base/Dependencies.toml, hl7v23/Ballerina.toml, hl7v23/Dependencies.toml, hl7v23/Package.md
=> [Release - health.hl7v23:1.0.2] Prepare for release

hl7v23/Ballerina.toml, hl7v23/Dependencies.toml, hl7v23/Module.md, hl7v23/Package.md
=> [Release - health.hl7v23:1.0.3] Prepare for release

base/parser.bal
=> Handle both MLLP and non-MLLP modes of HL7 messages

base/Ballerina.toml, base/Dependencies.toml, base/Module.md
=> Fix module md

base/parser.bal, utils/v2tofhirr4/Dependencies.toml, utils/v2tofhirr4/Module.md, utils/v2tofhirr4/Package.md, utils/v2tofhirr4/helper_enums.bal, utils/v2tofhirr4/mappings.bal, utils/v2tofhirr4/utilities.bal
=> Add sample to package md and support new line delimited segments

hl7v23/Ballerina.toml, hl7v23/Dependencies.toml, hl7v231/Ballerina.toml, hl7v231/Dependencies.toml, hl7v24/Ballerina.toml, hl7v24/Dependencies.toml, hl7v25/Ballerina.toml, hl7v25/Dependencies.toml, hl7v251/Ballerina.toml, hl7v251/Dependencies.toml, hl7v26/Ballerina.toml, hl7v26/Dependencies.toml, hl7v27/Ballerina.toml, hl7v27/Dependencies.toml, hl7v271/Ballerina.toml, hl7v271/Dependencies.toml, hl7v28/Ballerina.toml, hl7v28/Dependencies.toml, utils/v2tofhirr4/Dependencies.toml
> $Subject
> https://github.com/wso2-enterprise/open-healthcare/issues/1243
=> Upgrade Ballerina version to 2201.5.0

base/Ballerina.toml, hl7v23/Ballerina.toml, hl7v231/Ballerina.toml, hl7v24/Ballerina.toml, hl7v25/Ballerina.toml, hl7v251/Ballerina.toml, hl7v26/Ballerina.toml, hl7v27/Ballerina.toml, hl7v271/Ballerina.toml, hl7v28/Ballerina.toml, utils/v2tofhirr4/Ballerina.toml
=> Prepare for next dev cycle

base/parser.bal, hl7v23/hl7_parser.bal, hl7v231/hl7_parser.bal, hl7v24/hl7_parser.bal, hl7v25/hl7_parser.bal, hl7v251/hl7_parser.bal, hl7v26/hl7_parser.bal, hl7v27/hl7_parser.bal, hl7v271/hl7_parser.bal, hl7v28/hl7_parser.bal
Related to https://github.com/wso2-enterprise/open-healthcare/issues/1250
=> Avoid wrapping of parse errors

utils/v2tofhirr4/Dependencies.toml, utils/v2tofhirr4/datatypes_mappings.bal, utils/v2tofhirr4/helper_enums.bal, utils/v2tofhirr4/helper_extensions.bal, utils/v2tofhirr4/helpers.bal, utils/v2tofhirr4/mapping_defs.bal, utils/v2tofhirr4/mappings.bal, utils/v2tofhirr4/utilities.bal
> This PR will add following implementations to the v2tofhir mapping lib.
- Add functionality to bind custom mapping functions
- Make mapping functions isolated
=> Add functionality to bind custom mapping functions

utils/v2tofhirr4/mapping_defs.bal, utils/v2tofhirr4/mappings.bal, utils/v2tofhirr4/utilities.bal
=> Rename custom segment mapper to suggested name

.github/workflows/cd-base.yml, .github/workflows/cd-hl7v23.yml, .github/workflows/cd-hl7v231.yml, .github/workflows/cd-hl7v24.yml, .github/workflows/cd-hl7v25.yml, .github/workflows/cd-hl7v251.yml, .github/workflows/cd-hl7v26.yml, .github/workflows/cd-hl7v27.yml, .github/workflows/cd-hl7v271.yml, .github/workflows/cd-hl7v28.yml, .github/workflows/cd-v2tofhirr4.yml
> [Fix issues related to CD workflows
> 1. Bumping multiple versions if they are equal in Ballerina.toml
> 2. Tag creation by default targets the main branch
=> Fix issues related to CD workflows

commons/Ballerina.toml, commons/Dependencies.toml
=> [Release hl7v2commons 1.0.0] Prepare for release

utils/v2tofhirr4/Dependencies.toml, utils/v2tofhirr4/datatypes_mappings.bal, utils/v2tofhirr4/helpers.bal, utils/v2tofhirr4/mapping_defs.bal, utils/v2tofhirr4/mappings.bal, utils/v2tofhirr4/utilities.bal
> This PR will fix some of the missing improvements suggested with https://github.com/ballerina-platform/module-ballerinax-health.hl7v2/pull/26 and adds isolated support for the v2tofhir module functions.
=> Fix suggested improvements on the v2tofhir module

base/tests/base_tests.bal, hl7v23/tests/parser_tests.bal, hl7v231/tests/parser_tests.bal, hl7v24/tests/parser_tests.bal, hl7v25/tests/parser_tests.bal, hl7v251/tests/parser_tests.bal, hl7v26/tests/parser_tests.bal, hl7v27/tests/parser_tests.bal, hl7v271/tests/parser_tests.bal, hl7v28/tests/parser_tests.bal, utils/v2tofhirr4/datatypes_mappings.bal, utils/v2tofhirr4/mapping_defs.bal, utils/v2tofhirr4/mappings.bal, utils/v2tofhirr4/utilities.bal
=> Add unit tests for Hl7 packages

base/Ballerina.toml, base/Dependencies.toml
=> Release hl7v2 v2.0.1

.github/workflows/cd-base.yml, .github/workflows/cd-hl7v23.yml, .github/workflows/cd-hl7v231.yml, .github/workflows/cd-hl7v24.yml, .github/workflows/cd-hl7v25.yml, .github/workflows/cd-hl7v251.yml, .github/workflows/cd-hl7v26.yml, .github/workflows/cd-hl7v27.yml, .github/workflows/cd-hl7v271.yml, .github/workflows/cd-hl7v28.yml, .github/workflows/cd-hl7v2commons.yml, .github/workflows/cd-v2tofhirr4.yml
=> Added fix for passing secrets

hl7v23/Ballerina.toml, hl7v23/Dependencies.toml
[Release hl7v23 v2.0.1] Prepare for release
=> [Release hl7v23 v2.0.1] Prepare for release

.github/workflows/build-executor.yml
Added separate ballerina builds for when the ballerina central environment is stage, dev and prod.
=> Added seperate builds for stage, dev, prod

hl7v231/Ballerina.toml, hl7v231/Dependencies.toml, hl7v231/Package.md
[Release hl7v231 v2.0.1] Prepare for release
=> [Release hl7v231 v2.0.1] Prepare for release

hl7v24/Ballerina.toml, hl7v24/Dependencies.toml, hl7v24/Package.md
[Release hl7v24 v2.0.1] Prepare for release
=> [Release hl7v24 v2.0.1] Prepare for release

hl7v251/Ballerina.toml, hl7v251/Dependencies.toml, hl7v251/Package.md
[Release hl7v251 v2.0.1] Prepare for release
=> [Release hl7v251 v2.0.1] Prepare for release

hl7v26/Ballerina.toml, hl7v26/Dependencies.toml, hl7v26/Package.md
[Release hl7v26 v2.0.1] Prepare for release
=> [Release hl7v26 v2.0.1] Prepare for release

hl7v27/Ballerina.toml, hl7v27/Dependencies.toml, hl7v27/Package.md
[Release hl7v27 v2.0.1] Prepare for release
=> [Release hl7v27 v2.0.1] Prepare for release

hl7v271/Ballerina.toml, hl7v271/Dependencies.toml, hl7v271/Package.md
[Release hl7v271 v2.0.1] Prepare for release
=> [Release hl7v271 v2.0.1] Prepare for release

hl7v28/Ballerina.toml, hl7v28/Dependencies.toml, hl7v28/Package.md
[Release hl7v28 v2.0.1] Prepare for release
=> [Release hl7v28 v2.0.1] Prepare for release

hl7v25/Ballerina.toml, hl7v25/Dependencies.toml, hl7v25/Package.md
[Release hl7v25 v2.0.1] Prepare for release
=> [Release hl7v25 v2.0.1] Prepare for release

commons/Ballerina.toml, commons/Dependencies.toml
[Release hl7v2commons v1.0.1] Prepare for release
=> [Release hl7v2commons v1.0.1] Prepare for release

utils/v2tofhirr4/Ballerina.toml, utils/v2tofhirr4/Dependencies.toml
[Release v2tofhir v2.0.2] Prepare for release
=> [Release v2tofhir v2.0.2] Prepare for release

base/Ballerina.toml, base/Dependencies.toml
[Release hl7v2 v2.0.1] Prepare for release
=> [Release hl7v2 v2.0.1] Prepare for release

base/Ballerina.toml, base/Dependencies.toml
[Release hl7v2 v2.0.1] Prepare for next dev cycle
=> [Release hl7v2 v2.0.1] Prepare for next dev cycle

hl7v23/Ballerina.toml, hl7v23/Dependencies.toml
[Release hl7v23 v2.0.1] Prepare for next dev cycle
=> [Release hl7v23 v2.0.1] Prepare for next dev cycle

.github/workflows/build-executor.yml
Fixed issue where the variable packageName is read as a string.
=> Fixed issues in making PR

base/Dependencies.toml, base/tests/base_tests.bal, base/utils.bal
Add fix for uninitialized variable issue comes with upgrading to Ballerina 8
=> Add fix for uninitialized variable issue

.github/workflows/ci.yml
=> Upgrade bal version in git ci pipeline

utils/v2tofhirr4/Dependencies.toml, utils/v2tofhirr4/datatypes_mappings.bal, utils/v2tofhirr4/helper_extensions.bal, utils/v2tofhirr4/mappings.bal, utils/v2tofhirr4/utilities.bal
=> Fix empty values returned with the transformed resources 

.github/workflows/build-executor.yml, .github/workflows/ci.yml
=> Upgrade ci-cd workflows to use bal 8.1

.github/workflows/build-executor.yml, .github/workflows/ci.yml, base/Ballerina.toml, base/Dependencies.toml
=> [Release hl7base v2.1.0] Prepare for release

hl7v23/Ballerina.toml, hl7v23/Dependencies.toml
=> [Release hl7v23 v2.1.0] Prepare for release

hl7v24/Ballerina.toml, hl7v24/Dependencies.toml
=> [Release hl7v24 v2.1.0] Prepare for release

hl7v25/Ballerina.toml, hl7v25/Dependencies.toml
=> [Release hl7v25 v2.1.0] Prepare for release

hl7v26/Ballerina.toml, hl7v26/Dependencies.toml
=> [Release hl7v26 v2.1.0] Prepare for release

hl7v28/Ballerina.toml, hl7v28/Dependencies.toml
=> [Release hl7v28 v2.1.0] Prepare for release

hl7v251/Ballerina.toml, hl7v251/Dependencies.toml
=> [Release hl7v251 v2.1.0] Prepare for release

hl7v271/Ballerina.toml, hl7v271/Dependencies.toml
=> [Release hl7v271 v2.1.0] Prepare for release

hl7v27/Ballerina.toml, hl7v27/Dependencies.toml
=> [Release hl7v27 v2.1.0] Prepare for release

hl7v231/Ballerina.toml, hl7v231/Dependencies.toml
=> [Release hl7v231 v2.1.0] Prepare for release

commons/Ballerina.toml, commons/Dependencies.toml
=> [Release hl7v2commons v1.1.0] Prepare for release

utils/v2tofhirr4/datatypes_mappings.bal, utils/v2tofhirr4/mappings.bal, utils/v2tofhirr4/utilities.bal
=> Fix multiple v2tofhir mapping issues

utils/v2tofhirr4/Ballerina.toml, utils/v2tofhirr4/Dependencies.toml
=> [Release v2tofhirr4 v2.1.0] Prepare for release

base/Module.md
Update samples with NM datatype change.
Related Issue: https://github.com/wso2-enterprise/open-healthcare/issues/1456
=> Update samples with NM datatype change

base/Ballerina.toml, base/Dependencies.toml
[Release hl7v2 v2.2.0] Prepare for release
=> [Release hl7v2 v2.2.0] Prepare for release

hl7v23/Ballerina.toml, hl7v23/Dependencies.toml, hl7v23/hl7_parser.bal
[Release hl7v23 v3.0.0] Prepare for release
=> [Release hl7v23 v3.0.0] Prepare for release

hl7v231/Ballerina.toml, hl7v231/Dependencies.toml, hl7v231/hl7_parser.bal
[Release hl7v231 v3.0.0] Prepare for release
=> [Release hl7v231 v3.0.0] Prepare for release

hl7v24/Ballerina.toml, hl7v24/Dependencies.toml, hl7v24/hl7_parser.bal
[Release hl7v24 v3.0.0] Prepare for release
=> [Release hl7v24 v3.0.0] Prepare for release

hl7v25/Ballerina.toml, hl7v25/Dependencies.toml, hl7v25/hl7_parser.bal
[Release hl7v25 v3.0.0] Prepare for release
=> [Release hl7v25 v3.0.0] Prepare for release

hl7v251/Ballerina.toml, hl7v251/Dependencies.toml, hl7v251/hl7_parser.bal
[Release hl7v251 v3.0.0] Prepare for release
=> [Release hl7v251 v3.0.0] Prepare for release

hl7v26/Ballerina.toml, hl7v26/Dependencies.toml, hl7v26/hl7_parser.bal
[Release hl7v26 v3.0.0] Prepare for release
=> [Release hl7v26 v3.0.0] Prepare for release

hl7v27/Ballerina.toml, hl7v27/Dependencies.toml, hl7v27/hl7_parser.bal
[Release hl7v27 v3.0.0] Prepare for release
=> [Release hl7v27 v3.0.0] Prepare for release

hl7v271/Ballerina.toml, hl7v271/Dependencies.toml, hl7v271/hl7_parser.bal
[Release hl7v271 v3.0.0] Prepare for release
=> [Release hl7v271 v3.0.0] Prepare for release

hl7v28/Ballerina.toml, hl7v28/Dependencies.toml, hl7v28/hl7_parser.bal
[Release hl7v28 v3.0.0] Prepare for release
=> [Release hl7v28 v3.0.0] Prepare for release

utils/v2tofhirr4/Dependencies.toml, utils/v2tofhirr4/datatypes_mappings.bal, utils/v2tofhirr4/helper_extensions.bal, utils/v2tofhirr4/mapping_defs.bal, utils/v2tofhirr4/mappings.bal, utils/v2tofhirr4/utilities.bal
> $Subject
> Related issues: 
> https://github.com/wso2-enterprise/open-healthcare/issues/1193
=> Adding missing mappings

utils/v2tofhirr4/Ballerina.toml, utils/v2tofhirr4/Dependencies.toml
=> [Release v2tofhirr4 v2.2.0] Prepare for release

utils/v2tofhirr4/mappings.bal
=> Fix cast issue with pv2 mapping

utils/v2tofhirr4/Dependencies.toml, utils/v2tofhirr4/utilities.bal
Fix issues
- https://github.com/wso2-enterprise/open-healthcare/issues/1492
=> Fix issues

base/tests/base_tests.bal, base/tests/test_utils.bal, utils/v2tofhirr4/Ballerina.toml, utils/v2tofhirr4/Dependencies.toml, utils/v2tofhirr4/mappings.bal, utils/v2tofhirr4/tests/mapping_tests.bal, utils/v2tofhirr4/utilities.bal
> This PR will add more test cases for the base HL7 module and the v2tofhir module. There is a issue[1] with the bal side when the tests are added. Once it's fixed v2tofhir module will be updated.
[1] - https://github.com/wso2-enterprise/internal-support-ballerina/issues/559
=> Add more test cases for hl7 modules

.github/workflows/build-executor.yml, .github/workflows/ci.yml, base/Ballerina.toml, base/Dependencies.toml
=> Upgrade to ballerina 9

hl7v23/Ballerina.toml, hl7v23/Dependencies.toml, hl7v231/Ballerina.toml, hl7v231/Dependencies.toml, hl7v24/Ballerina.toml, hl7v24/Dependencies.toml, hl7v25/Ballerina.toml, hl7v25/Dependencies.toml, hl7v251/Ballerina.toml, hl7v251/Dependencies.toml, hl7v26/Ballerina.toml, hl7v26/Dependencies.toml, hl7v27/Ballerina.toml, hl7v27/Dependencies.toml, hl7v271/Ballerina.toml, hl7v271/Dependencies.toml, hl7v28/Ballerina.toml, hl7v28/Dependencies.toml
- remove unnecessary dependency
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, …
=> Upgrade to bal9

commons/Ballerina.toml, commons/Dependencies.toml
remove unnecessary dependency declarartion
> Link(s) to product documentation that addresses the changes of this PR. If no doc …
=> Upgrade to bal9 - hl7 commons

.github/workflows/build-executor.yml, .github/workflows/ci.yml, .github/workflows/daily-build.yml, README.md
Related Issue: https://github.com/wso2-enterprise/open-healthcare/issues/1595
=> Add daily Codecov upload workflow

.github/workflows/daily-build.yml
=> Increase memory

utils/v2tofhirr4/Dependencies.toml, utils/v2tofhirr4/config.bal, utils/v2tofhirr4/mappings.bal, utils/v2tofhirr4/tests/mapping_tests.bal, utils/v2tofhirr4/utilities.bal
> $Subject.
> Related issue: https://github.com/wso2-enterprise/open-healthcare/issues/1594
=> Feature v2tofhir custom mappings service impl

utils/v2tofhirr4/Ballerina.toml, utils/v2tofhirr4/Dependencies.toml, utils/v2tofhirr4/mappings.bal
=> Fix v2tofhir issues in bal 8

.github/workflows/build-executor.yml, .github/workflows/cd-v2tofhirr4.yml
=> Allow triggering CD pipeline with Ballerina version selection

utils/v2tofhirr4/Ballerina.toml
=> Change bal version

utils/v2tofhirr4/Ballerina.toml, utils/v2tofhirr4/Dependencies.toml
=> Fix inconsistencies with dependency toml

utils/v2tofhirr4/Ballerina.toml, utils/v2tofhirr4/Dependencies.toml, utils/v2tofhirr4/tests/mapping_tests.bal
=> [Release v2tofhirr4 3.0.0] Prepare for release

base/Ballerina.toml, hl7v23/Ballerina.toml, hl7v23/Dependencies.toml
> related issue: https://github.com/wso2-enterprise/open-healthcare/issues/1608
release of `hl7v23` module
=> Prepare for the release[v3.0.3]

base/Dependencies.toml, commons/Ballerina.toml, commons/Dependencies.toml, utils/v2tofhirr4/Ballerina.toml, utils/v2tofhirr4/Dependencies.toml
> `commons:v1.1.2`
`v2tofhirr4:2.2.4`
=> Prepare for release.

utils/v2tofhirr4/Ballerina.toml, utils/v2tofhirr4/Dependencies.toml, utils/v2tofhirr4/tests/mapping_tests.bal
=> Prepare for release [v2tofhirr4:3.0.1]

utils/v2tofhirr4/Ballerina.toml, utils/v2tofhirr4/Dependencies.toml, utils/v2tofhirr4/tests/mapping_tests.bal
=> [Commons] Sync with main

.github/workflows/ci.yml, .github/workflows/daily-build-executor.yml, hl7v23/Dependencies.toml, hl7v231/Dependencies.toml, hl7v24/Dependencies.toml, hl7v25/Dependencies.toml, hl7v251/Dependencies.toml, hl7v26/Dependencies.toml, hl7v27/Dependencies.toml, hl7v271/Dependencies.toml, hl7v28/Dependencies.toml
=> Update Dependencies.toml for bal8

.github/workflows/ci.yml, .github/workflows/daily-build-executor.yml
=> Update CI build bal version

hl7v23/hl7_parser.bal, hl7v23/tests/parser_tests.bal
=> Fix issue with not populating nested segment groups

.github/workflows/daily-build-executor.yml, utils/v2tofhirr4/Dependencies.toml
> Updated dependancy toml after verifying locally. Pushing to ensure the correct dependancy versions are getting fetched in the build
=> Update dependancy toml

base/Dependencies.toml, base/hl7_client.bal, hl7v231/hl7_parser.bal, hl7v24/Dependencies.toml, hl7v24/hl7_parser.bal, hl7v25/hl7_parser.bal, hl7v251/hl7_parser.bal, hl7v26/hl7_parser.bal, hl7v27/hl7_parser.bal, hl7v271/hl7_parser.bal, hl7v28/hl7_parser.bal
fix:https://github.com/wso2-enterprise/open-healthcare/issues/1699
> $subject, add ACK message processing support for hl7V24
=> Fix version resolve issue in hl7Client

base/hl7_client.bal
> This will make the hl7Client implementation align with Ballerina standard for network interactions.
> Make `sendMessage()` method a remote function.
=> Make HL7 Client Deprecated

hl7v23/Ballerina.toml, hl7v23/Dependencies.toml, hl7v23/utils.bal, hl7v231/utils.bal, hl7v24/Ballerina.toml, hl7v24/Dependencies.toml, hl7v25/utils.bal, hl7v251/utils.bal, hl7v26/utils.bal, hl7v27/utils.bal, hl7v271/utils.bal, hl7v28/utils.bal
=> Add missing messages

hl7v23/Dependencies.toml, hl7v231/Ballerina.toml, hl7v231/Dependencies.toml, hl7v24/Dependencies.toml, hl7v25/Ballerina.toml, hl7v25/Dependencies.toml, hl7v251/Ballerina.toml, hl7v251/Dependencies.toml, hl7v26/Ballerina.toml, hl7v26/Dependencies.toml, hl7v27/Ballerina.toml, hl7v27/Dependencies.toml, hl7v271/Ballerina.toml, hl7v271/Dependencies.toml, hl7v28/Ballerina.toml, hl7v28/Dependencies.toml
> $subject
> Update dependancies and release `hl7v2X` Ballerina packages;
=> [Release-hl7v2X-v3.2.0] Prepare for release

utils/v2tofhirr4/Ballerina.toml, utils/v2tofhirr4/Dependencies.toml, utils/v2tofhirr4/helper_extensions.bal, utils/v2tofhirr4/mapping_defs.bal, utils/v2tofhirr4/tests/mapping_tests.bal, utils/v2tofhirr4/type_defs.bal
> $subject , apply Ballerina formatter
=> [v2tofhir][release-v3.2.0] Prepare for release

hl7v23/Dependencies.toml, hl7v231/Dependencies.toml, hl7v24/Dependencies.toml, hl7v25/Dependencies.toml, hl7v251/Dependencies.toml, hl7v26/Dependencies.toml, hl7v27/Dependencies.toml, hl7v271/Dependencies.toml, hl7v28/Dependencies.toml
> $subject
> Ensure Ballerina 12 compatibility
> https://github.com/wso2-enterprise/open-healthcare/issues/1722
=> Update hl7 base

base/Ballerina.toml, base/Dependencies.toml, base/constants.bal
=> Fix issues with base build

utils/v2tofhirr4/Dependencies.toml, utils/v2tofhirr4/datatypes_mappings.bal, utils/v2tofhirr4/mappings.bal, utils/v2tofhirr4/tests/mapping_tests.bal, utils/v2tofhirr4/utilities.bal
> fix: https://github.com/wso2-enterprise/open-healthcare/issues/1736
=> Add Utility to Convert HL7 Datetime to R4 Datetime format

utils/v2tofhirr4/mappings.bal, utils/v2tofhirr4/utilities.bal
=> Handle nested segments, minor fixes

base/README.md, base/annotations.bal, base/parser.bal, base/registry.bal, base/utils.bal
> $Subject
> Related issue: https://github.com/wso2-enterprise/open-healthcare/issues/1721
=> Add support for Z segments and fix custom segment reg issue

base/utils.bal
=> Fix issue with accessibility of newModule function
